name: Build and Deploy

on:
  push:
    tags:
      # Match a tag with the format v1.0.0
      - "v[0-9]+.[0-9]+.[0-9]"
  workflow_dispatch:
    inputs:
      skip-jobs:
        description: "Space-separated list of jobs to skip"
        required: false
        default: ""

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      skip-build-and-push-docker: ${{ steps.set-skip-build-and-push-docker.outputs.skip }}
    steps:
      - name: Determine Jobs to Skip
        id: set-skip-build-and-push-docker
        run: |
          if [[ "${{ github.event.inputs['skip-jobs'] }}" == *"build-and-push-docker"* ]]; then
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "skip=false" >> $GITHUB_ENV
          fi

  build-and-push-docker:
    if: ${{ !contains(github.event.inputs['skip-jobs'], 'build-and-push-docker') }}
    runs-on: ubuntu-latest
    needs: initialization
    strategy:
      matrix:
        ruby_version:
          - 3.4.6
          - 3.3.9
          - 3.3.4
          - 3.2.9
          - 3.1.7
          - 3.0.7
          - 2.7.8
        ubuntu_version:
          - 24.04
          - 22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/ruby:${{ matrix.ruby_version }}-ubuntu${{ matrix.ubuntu_version }}-${{ github.ref_name }}
            ${{ secrets.DOCKER_USER }}/ruby:${{ matrix.ruby_version }}-ubuntu${{ matrix.ubuntu_version }}
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          cache: true

  build-and-push-adminer:
    if: ${{ !contains(github.event.inputs['skip-jobs'], 'build-and-push-adminer') }}
    runs-on: ubuntu-latest
    needs: initialization
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Adminer Image
        uses: docker/build-push-action@v6
        with:
          context: ./build/adminer
          file: ./build/adminer/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/adminer:latest
            ${{ secrets.DOCKER_USER }}/adminer:${{ github.ref_name }}
          build-args: |
            ADMINER_VERSION=latest

  update-coder-template:
    # Conditional execution based on skip-jobs input and initialization job output
    # Only runs if skip-jobs does not contain 'update-coder-template'
    # OR build-and-push-docker job is successful
    if: ${{ !contains(github.event.inputs['skip-jobs'], 'update-coder-template') || needs.initialization.outputs.skip-build-and-push-docker == 'true' || success() }}
    runs-on: ubuntu-latest
    needs:
      - initialization
      - build-and-push-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Coder Template
        uses: matifali/update-coder-template@v3
        with:
          id: ruby
          dir: .
          url: https://embold.dev
          name: ${{ github.ref_name }}
          message: "Uploaded by GitHub Actions. Release notes: https://github.com/emboldagency/docker-ruby/releases/tag/${{ github.ref_name }}"
          coder_session_token: ${{ secrets.CODER_TOKEN }}
